#+title: Assignment 10
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css" />
#+OPTIONS: html-style:nil H:2 toc:nil todo:nil author:nil date:nil
#+HTML_LINK_HOME: ../../index.html
The following assignment is due *Thursday April 16 by 8:00 PM*.  Your
solutions should be submitted via Gradescope as a single pdf.  They
must be exceptionally neat (or typed) and the final answer in your
solution to each problem must be abundantly clear, e.g., surrounded in
a box.  Also make sure to cite your sources per the instructions in
the course manual.

The problems are taken from the workbook /Problems and Exercises/
included in the course material based on version: [[https://nmmull.github.io/cs132-s26/workbook/v004.pdf][*v0.0.4*]]

These problems are based on problems that come from /Linear Algebra
and it's Applications/ by David C. Lay, Steven R. Lay, and Judi
J. McDonald.  As a reminder, we recommend this textbook as a source
for supplementary exercises.

All problems that are /not/ bolded are review for the midterm exam.
In particular, the topics covered in the bolded problems will not
appear on the midterm exam.

*Basic Problems:* 10.4, 10.11, 11.1, 11.2

*True/False:* 10.19, 10.20, 10.25, 10.28, 11.10, 11.11

*More Difficult Problems:* 10.39, 10.40, 11.15

*Challenge Problems (Optional):* 10.52, 10.54
