#+title: Assignment 7
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css" />
#+OPTIONS: html-style:nil H:2 toc:nil todo:nil author:nil date:nil
#+HTML_LINK_HOME: ../../index.html
The following assignment is due *Thursday March 26 by 8:00 PM*.
Your solutions should be submitted via Gradescope as a single pdf.
They must be exceptionally neat (or typed) and the final answer in
your solution to each problem must be abundantly clear, e.g.,
surrounded in a box.  Also make sure to cite your sources per the
instructions in the course manual.

The problems are taken from the workbook /Problems and Exercises/
included in the course material based on version: [[https://nmmull.github.io/cs132-s26/workbook/v004.pdf][*v0.0.4*]]

These problems are based on problems that come from /Linear Algebra
and it's Applications/ by David C. Lay, Steven R. Lay, and Judi
J. McDonald.  As a reminder, we recommend this textbook as a source
for supplementary exercises.  The relevant sections for this
assignment are: *2.7*. *4.9*

*Basic Problems:* 8.1, 8.2, 8.5, 8.6, 8.8, 8.14

*True/False:* 8.17, 8.20, 8.21, 8.22

*More Difficult Problems:* 8.24, 8.27

*Challenge Problems (Optional):* 8.28, 8.29
