#+title: Assignment 3
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css" />
#+OPTIONS: html-style:nil H:2 toc:nil todo:nil author:nil date:nil
#+HTML_LINK_HOME: ../../index.html
The following assignment is due *Thursday February 12 by 8:00 PM*.
Your solutions should be submitted via Gradescope as a single pdf.
They must be exceptionally neat (or typed) and the final answer in
your solution to each problem must be abundantly clear, e.g.,
surrounded in a box.  Also make sure to cite your sources per the
instructions in the course manual.

The problems are taken from the workbook /Problems and Exercises/
included in the course material based on version: [[https://nmmull.github.io/cs132-s26/workbook/v003.pdf][*v0.0.3*]]

These problems are based on problems that come from /Linear Algebra
and it's Applications/ by David C. Lay, Steven R. Lay, and Judi
J. McDonald.  As a reminder, we recommend this textbook as a source
for supplementary exercises.  The relevant sections for this
assignment are: *1.4*, *1.7*

*Basic Problems:* 3.3, 3.4, 3.5, 3.6, 3.11, 3.12, 4.2, 4.4, 4.6

*True/False:* 3.16, 3.19, 3.20, 3.23, 4.7, 4.9, 4.12, 4.14, 4.15

*More Difficult Problems:* 3.27, 3.30, 4.16, 4.17, 4.23

*Challenge Problems (Optional):* 3.31, 4.26
