#+title: Assignment 5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css" />
#+OPTIONS: html-style:nil H:2 toc:nil todo:nil author:nil date:nil
#+HTML_LINK_HOME: ../../index.html
The following assignment is due *Thursday February 26 by 8:00 PM*.
Your solutions should be submitted via Gradescope as a single pdf.
They must be exceptionally neat (or typed) and the final answer in
your solution to each problem must be abundantly clear, e.g.,
surrounded in a box.  Also make sure to cite your sources per the
instructions in the course manual.

The problems are taken from the workbook /Problems and Exercises/
included in the course material based on version: [[https://nmmull.github.io/cs132-s26/workbook/v004.pdf][*v0.0.4*]]

These problems are based on problems that come from /Linear Algebra
and it's Applications/ by David C. Lay, Steven R. Lay, and Judi
J. McDonald.  As a reminder, we recommend this textbook as a source
for supplementary exercises.  The relevant sections for this
assignment are: *1.9*, *2.1*

*Basic Problems:* 5.22, 5.23, 5.25, 5.27, 6.2, 6.5, 6.6, 6.7, 6.8, 6.18

*True/False:* 5.37, 5.38, 5.39, 6.33, 6.36, 6.42, 6.47, 6.49

*More Difficult Problems:* 5.57, 6.70, 6.71, 6.72

*Challenge Problems (Optional):* 6.76, 6.77
