#+title: Assignment 6
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css" />
#+OPTIONS: html-style:nil H:2 toc:nil todo:nil author:nil date:nil
#+HTML_LINK_HOME: ../../index.html
The following assignment is due *Thursday March 19 by 8:00 PM*.
Your solutions should be submitted via Gradescope as a single pdf.
They must be exceptionally neat (or typed) and the final answer in
your solution to each problem must be abundantly clear, e.g.,
surrounded in a box.  Also make sure to cite your sources per the
instructions in the course manual.

The problems are taken from the workbook /Problems and Exercises/
included in the course material based on version: [[https://nmmull.github.io/cs132-s26/workbook/v004.pdf][*v0.0.4*]]

These problems are based on problems that come from /Linear Algebra
and it's Applications/ by David C. Lay, Steven R. Lay, and Judi
J. McDonald.  As a reminder, we recommend this textbook as a source
for supplementary exercises.  The relevant sections for this
assignment are: *2.2*, *2.3*, *2.5*

*Basic Problems:* 6.19, 6.20, 6.23, 6.24, 6.30, 7.2, 7.3

*True/False:* 6.40, 6.42, 6.43, 6.48, 7.6, 7.7

*More Difficult Problems:* 6.65, 6.67, 6.73, 7.10

*Challenge Problems (Optional):* 6.76, 6.79
