#+title: Assignment 9
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css" />
#+OPTIONS: html-style:nil H:2 toc:nil todo:nil author:nil date:nil
#+HTML_LINK_HOME: ../../index.html
The following assignment is due *Thursday April 9 by 8:00 PM*.
Your solutions should be submitted via Gradescope as a single pdf.
They must be exceptionally neat (or typed) and the final answer in
your solution to each problem must be abundantly clear, e.g.,
surrounded in a box.  Also make sure to cite your sources per the
instructions in the course manual.

The problems are taken from the workbook /Problems and Exercises/
included in the course material based on version: [[https://nmmull.github.io/cs132-s26/workbook/v004.pdf][*v0.0.4*]]

These problems are based on problems that come from /Linear Algebra
and it's Applications/ by David C. Lay, Steven R. Lay, and Judi
J. McDonald.  As a reminder, we recommend this textbook as a source
for supplementary exercises.

All problems that are /not/ bolded are review for the midterm exam.
In particular, the topics covered in the bolded problems will not
appear on the midterm exam.

*Basic Problems:* 1.35, 2.11, 2.18, 3.13, 4.3, 5.3, 5.13, 5.19, 5.21, 5.26, 5.30, 6.4, 6.21, 6.25, 6.31, 7.4, 8.3, 8.7, 9.7, 9.9, 9.18, *10.1*, *10.3*, *10.8*, *10.9*

*True/False:* 3.17, 3.25, 4.13, 5.40, 6.35, 6.40, 6.55, 6.56, 6.57, 6.63, 7.5, 8.15, 8.23, 9.29, 9.30, *10.22*, *10.23*, *10.24*

*More Difficult Problems:* 1.65, 2.26, 4.24, 5.51, 6.67, 6.68, 6.73, 8.26, 9.40, *10.35*, *10.38*

*Challenge Problems (Optional):* *10.52*
